[package]
name = "sdly"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
easy-gltf = "1.1.5"
gltf = "1.4.1"
image = "0.25.6"
sdl3 = { version = "0.14.16", features = ["build-from-source"] }
ultraviolet = "0.9.2"
